version: "3"
services:

  # Oracle service (label used to access the service container)
  database:

    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:latest

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: my_user
      APP_USER_PASSWORD: my_password_which_I_really_should_change

    # Forward Oracle port
    ports:
      - 1521:1521