CREATE TABLE DIRT.ACCOUNT
(
    IDT_ACCOUNT NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME VARCHAR2(60),
    DOCUMENT VARCHAR2(14),
    NUM_ACCOUNT VARCHAR2(20),
    NUM_ACCOUNT_AGENCY VARCHAR2(6),
    NUM_ACCOUNT_BANK VARCHAR2(4),
    COD_ACCOUNT_TYPE CHAR(1)
);


CREATE TABLE DIRT.TRANSACTION
(
    IDT_TRANSACTION NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NUM_IP          VARCHAR2(15),
    NUM_AMOUNT      NUMBER(14,2),
    NUM_TAX         NUMBER(3,2),
    CONSTRAINT IDT_ACCOUNT_FK FOREIGN KEY (IDT_ACCOUNT) REFERENCES DIRT.ACCOUNT (IDT_ACCOUNT)
);